namespace MacRobert.ValueObjects.Currencies;

internal static class CurrencyData
{
    public static readonly Currency[] AllCurrencies = new Currency[]
    {
        new Currency(Iso:"AFN", Name:"Afghani", Precision: 2),
        new Currency(Iso:"EUR", Name:"Euro", Precision: 2),
        new Currency(Iso:"ALL", Name:"Lek", Precision: 2),
        new Currency(Iso:"DZD", Name:"Algerian Dinar", Precision: 2),
        new Currency(Iso:"USD", Name:"US Dollar", Precision: 2),
        new Currency(Iso:"AOA", Name:"Kwanza", Precision: 2),
        new Currency(Iso:"XCD", Name:"East Caribbean Dollar", Precision: 2),
        new Currency(Iso:"ARS", Name:"Argentine Peso", Precision: 2),
        new Currency(Iso:"AMD", Name:"Armenian Dram", Precision: 2),
        new Currency(Iso:"AWG", Name:"Aruban Florin", Precision: 2),
        new Currency(Iso:"AUD", Name:"Australian Dollar", Precision: 2),
        new Currency(Iso:"AZN", Name:"Azerbaijan Manat", Precision: 2),
        new Currency(Iso:"BSD", Name:"Bahamian Dollar", Precision: 2),
        new Currency(Iso:"BHD", Name:"Bahraini Dinar", Precision: 3),
        new Currency(Iso:"BDT", Name:"Taka", Precision: 2),
        new Currency(Iso:"BBD", Name:"Barbados Dollar", Precision: 2),
        new Currency(Iso:"BYN", Name:"Belarusian Ruble", Precision: 2),
        new Currency(Iso:"BZD", Name:"Belize Dollar", Precision: 2),
        new Currency(Iso:"XOF", Name:"CFA Franc BCEAO", Precision: 0),
        new Currency(Iso:"BMD", Name:"Bermudian Dollar", Precision: 2),
        new Currency(Iso:"INR", Name:"Indian Rupee", Precision: 2),
        new Currency(Iso:"BTN", Name:"Ngultrum", Precision: 2),
        new Currency(Iso:"BOB", Name:"Boliviano", Precision: 2),
        new Currency(Iso:"BOV", Name:"Mvdol", Precision: 2),
        new Currency(Iso:"BAM", Name:"Convertible Mark", Precision: 2),
        new Currency(Iso:"BWP", Name:"Pula", Precision: 2),
        new Currency(Iso:"NOK", Name:"Norwegian Krone", Precision: 2),
        new Currency(Iso:"BRL", Name:"Brazilian Real", Precision: 2),
        new Currency(Iso:"BND", Name:"Brunei Dollar", Precision: 2),
        new Currency(Iso:"BGN", Name:"Bulgarian Lev", Precision: 2),
        new Currency(Iso:"BIF", Name:"Burundi Franc", Precision: 0),
        new Currency(Iso:"CVE", Name:"Cabo Verde Escudo", Precision: 2),
        new Currency(Iso:"KHR", Name:"Riel", Precision: 2),
        new Currency(Iso:"XAF", Name:"CFA Franc BEAC", Precision: 0),
        new Currency(Iso:"CAD", Name:"Canadian Dollar", Precision: 2),
        new Currency(Iso:"KYD", Name:"Cayman Islands Dollar", Precision: 2),
        new Currency(Iso:"CLP", Name:"Chilean Peso", Precision: 0),
        new Currency(Iso:"CLF", Name:"Unidad de Fomento", Precision: 4),
        new Currency(Iso:"CNY", Name:"Yuan Renminbi", Precision: 2),
        new Currency(Iso:"COP", Name:"Colombian Peso", Precision: 2),
        new Currency(Iso:"COU", Name:"Unidad de Valor Real", Precision: 2),
        new Currency(Iso:"KMF", Name:"Comorian Franc ", Precision: 0),
        new Currency(Iso:"CDF", Name:"Congolese Franc", Precision: 2),
        new Currency(Iso:"NZD", Name:"New Zealand Dollar", Precision: 2),
        new Currency(Iso:"CRC", Name:"Costa Rican Colon", Precision: 2),
        new Currency(Iso:"HRK", Name:"Kuna", Precision: 2),
        new Currency(Iso:"CUP", Name:"Cuban Peso", Precision: 2),
        new Currency(Iso:"CUC", Name:"Peso Convertible", Precision: 2),
        new Currency(Iso:"ANG", Name:"Netherlands Antillean Guilder", Precision: 2),
        new Currency(Iso:"CZK", Name:"Czech Koruna", Precision: 2),
        new Currency(Iso:"DKK", Name:"Danish Krone", Precision: 2),
        new Currency(Iso:"DJF", Name:"Djibouti Franc", Precision: 0),
        new Currency(Iso:"DOP", Name:"Dominican Peso", Precision: 2),
        new Currency(Iso:"EGP", Name:"Egyptian Pound", Precision: 2),
        new Currency(Iso:"SVC", Name:"El Salvador Colon", Precision: 2),
        new Currency(Iso:"ERN", Name:"Nakfa", Precision: 2),
        new Currency(Iso:"SZL", Name:"Lilangeni", Precision: 2),
        new Currency(Iso:"ETB", Name:"Ethiopian Birr", Precision: 2),
        new Currency(Iso:"FKP", Name:"Falkland Islands Pound", Precision: 2),
        new Currency(Iso:"FJD", Name:"Fiji Dollar", Precision: 2),
        new Currency(Iso:"XPF", Name:"CFP Franc", Precision: 0),
        new Currency(Iso:"GMD", Name:"Dalasi", Precision: 2),
        new Currency(Iso:"GEL", Name:"Lari", Precision: 2),
        new Currency(Iso:"GHS", Name:"Ghana Cedi", Precision: 2),
        new Currency(Iso:"GIP", Name:"Gibraltar Pound", Precision: 2),
        new Currency(Iso:"GTQ", Name:"Quetzal", Precision: 2),
        new Currency(Iso:"GBP", Name:"Pound Sterling", Precision: 2),
        new Currency(Iso:"GNF", Name:"Guinean Franc", Precision: 0),
        new Currency(Iso:"GYD", Name:"Guyana Dollar", Precision: 2),
        new Currency(Iso:"HTG", Name:"Gourde", Precision: 2),
        new Currency(Iso:"HNL", Name:"Lempira", Precision: 2),
        new Currency(Iso:"HKD", Name:"Hong Kong Dollar", Precision: 2),
        new Currency(Iso:"HUF", Name:"Forint", Precision: 2),
        new Currency(Iso:"ISK", Name:"Iceland Krona", Precision: 0),
        new Currency(Iso:"IDR", Name:"Rupiah", Precision: 2),
        new Currency(Iso:"IRR", Name:"Iranian Rial", Precision: 2),
        new Currency(Iso:"IQD", Name:"Iraqi Dinar", Precision: 3),
        new Currency(Iso:"ILS", Name:"New Israeli Sheqel", Precision: 2),
        new Currency(Iso:"JMD", Name:"Jamaican Dollar", Precision: 2),
        new Currency(Iso:"JPY", Name:"Yen", Precision: 0),
        new Currency(Iso:"JOD", Name:"Jordanian Dinar", Precision: 3),
        new Currency(Iso:"KZT", Name:"Tenge", Precision: 2),
        new Currency(Iso:"KES", Name:"Kenyan Shilling", Precision: 2),
        new Currency(Iso:"KPW", Name:"North Korean Won", Precision: 2),
        new Currency(Iso:"KRW", Name:"Won", Precision: 0),
        new Currency(Iso:"KWD", Name:"Kuwaiti Dinar", Precision: 3),
        new Currency(Iso:"KGS", Name:"Som", Precision: 2),
        new Currency(Iso:"LAK", Name:"Lao Kip", Precision: 2),
        new Currency(Iso:"LBP", Name:"Lebanese Pound", Precision: 2),
        new Currency(Iso:"LSL", Name:"Loti", Precision: 2),
        new Currency(Iso:"ZAR", Name:"Rand", Precision: 2),
        new Currency(Iso:"LRD", Name:"Liberian Dollar", Precision: 2),
        new Currency(Iso:"LYD", Name:"Libyan Dinar", Precision: 3),
        new Currency(Iso:"CHF", Name:"Swiss Franc", Precision: 2),
        new Currency(Iso:"MOP", Name:"Pataca", Precision: 2),
        new Currency(Iso:"MKD", Name:"Denar", Precision: 2),
        new Currency(Iso:"MGA", Name:"Malagasy Ariary", Precision: 2),
        new Currency(Iso:"MWK", Name:"Malawi Kwacha", Precision: 2),
        new Currency(Iso:"MYR", Name:"Malaysian Ringgit", Precision: 2),
        new Currency(Iso:"MVR", Name:"Rufiyaa", Precision: 2),
        new Currency(Iso:"MRU", Name:"Ouguiya", Precision: 2),
        new Currency(Iso:"MUR", Name:"Mauritius Rupee", Precision: 2),
        new Currency(Iso:"MXN", Name:"Mexican Peso", Precision: 2),
        new Currency(Iso:"MXV", Name:"Mexican Unidad de Inversion (UDI)", Precision: 2),
        new Currency(Iso:"MDL", Name:"Moldovan Leu", Precision: 2),
        new Currency(Iso:"MNT", Name:"Tugrik", Precision: 2),
        new Currency(Iso:"MAD", Name:"Moroccan Dirham", Precision: 2),
        new Currency(Iso:"MZN", Name:"Mozambique Metical", Precision: 2),
        new Currency(Iso:"MMK", Name:"Kyat", Precision: 2),
        new Currency(Iso:"NAD", Name:"Namibia Dollar", Precision: 2),
        new Currency(Iso:"NPR", Name:"Nepalese Rupee", Precision: 2),
        new Currency(Iso:"NIO", Name:"Cordoba Oro", Precision: 2),
        new Currency(Iso:"NGN", Name:"Naira", Precision: 2),
        new Currency(Iso:"OMR", Name:"Rial Omani", Precision: 3),
        new Currency(Iso:"PKR", Name:"Pakistan Rupee", Precision: 2),
        new Currency(Iso:"PAB", Name:"Balboa", Precision: 2),
        new Currency(Iso:"PGK", Name:"Kina", Precision: 2),
        new Currency(Iso:"PYG", Name:"Guarani", Precision: 0),
        new Currency(Iso:"PEN", Name:"Sol", Precision: 2),
        new Currency(Iso:"PHP", Name:"Philippine Peso", Precision: 2),
        new Currency(Iso:"PLN", Name:"Zloty", Precision: 2),
        new Currency(Iso:"QAR", Name:"Qatari Rial", Precision: 2),
        new Currency(Iso:"RON", Name:"Romanian Leu", Precision: 2),
        new Currency(Iso:"RUB", Name:"Russian Ruble", Precision: 2),
        new Currency(Iso:"RWF", Name:"Rwanda Franc", Precision: 0),
        new Currency(Iso:"SHP", Name:"Saint Helena Pound", Precision: 2),
        new Currency(Iso:"WST", Name:"Tala", Precision: 2),
        new Currency(Iso:"STN", Name:"Dobra", Precision: 2),
        new Currency(Iso:"SAR", Name:"Saudi Riyal", Precision: 2),
        new Currency(Iso:"RSD", Name:"Serbian Dinar", Precision: 2),
        new Currency(Iso:"SCR", Name:"Seychelles Rupee", Precision: 2),
        new Currency(Iso:"SLL", Name:"Leone", Precision: 2),
        new Currency(Iso:"SGD", Name:"Singapore Dollar", Precision: 2),
        new Currency(Iso:"SBD", Name:"Solomon Islands Dollar", Precision: 2),
        new Currency(Iso:"SOS", Name:"Somali Shilling", Precision: 2),
        new Currency(Iso:"SSP", Name:"South Sudanese Pound", Precision: 2),
        new Currency(Iso:"LKR", Name:"Sri Lanka Rupee", Precision: 2),
        new Currency(Iso:"SDG", Name:"Sudanese Pound", Precision: 2),
        new Currency(Iso:"SRD", Name:"Surinam Dollar", Precision: 2),
        new Currency(Iso:"SEK", Name:"Swedish Krona", Precision: 2),
        new Currency(Iso:"CHE", Name:"WIR Euro", Precision: 2),
        new Currency(Iso:"CHW", Name:"WIR Franc", Precision: 2),
        new Currency(Iso:"SYP", Name:"Syrian Pound", Precision: 2),
        new Currency(Iso:"TWD", Name:"New Taiwan Dollar", Precision: 2),
        new Currency(Iso:"TJS", Name:"Somoni", Precision: 2),
        new Currency(Iso:"TZS", Name:"Tanzanian Shilling", Precision: 2),
        new Currency(Iso:"THB", Name:"Baht", Precision: 2),
        new Currency(Iso:"TOP", Name:"Pa'anga", Precision: 2),
        new Currency(Iso:"TTD", Name:"Trinidad and Tobago Dollar", Precision: 2),
        new Currency(Iso:"TND", Name:"Tunisian Dinar", Precision: 3),
        new Currency(Iso:"TRY", Name:"Turkish Lira", Precision: 2),
        new Currency(Iso:"TMT", Name:"Turkmenistan New Manat", Precision: 2),
        new Currency(Iso:"UGX", Name:"Uganda Shilling", Precision: 0),
        new Currency(Iso:"UAH", Name:"Hryvnia", Precision: 2),
        new Currency(Iso:"AED", Name:"UAE Dirham", Precision: 2),
        new Currency(Iso:"USN", Name:"US Dollar (Next day)", Precision: 2),
        new Currency(Iso:"UYU", Name:"Peso Uruguayo", Precision: 2),
        new Currency(Iso:"UYI", Name:"Uruguay Peso en Unidades Indexadas (UI)", Precision: 0),
        new Currency(Iso:"UYW", Name:"Unidad Previsional", Precision: 4),
        new Currency(Iso:"UZS", Name:"Uzbekistan Sum", Precision: 2),
        new Currency(Iso:"VUV", Name:"Vatu", Precision: 0),
        new Currency(Iso:"VES", Name:"Bolívar Soberano", Precision: 2),
        new Currency(Iso:"VND", Name:"Dong", Precision: 0),
        new Currency(Iso:"YER", Name:"Yemeni Rial", Precision: 2),
        new Currency(Iso:"ZMW", Name:"Zambian Kwacha", Precision: 2),
        new Currency(Iso:"ZWL", Name:"Zimbabwe Dollar", Precision: 2),
    };
}
