namespace MacRobert.ValueObjects.Countries;

internal static class CountryData
{
    public static readonly Country[] AllCountries =
    {
            new Country( Iso2 : "AF" , Iso3 : "AFG", Name : "Afghanistan" ),
            new Country( Iso2 : "AX" , Iso3 : "ALA", Name : "Åland Islands" ),
            new Country( Iso2 : "AL" , Iso3 : "ALB", Name : "Albania" ),
            new Country( Iso2 : "DZ" , Iso3 : "DZA", Name : "Algeria" ),
            new Country( Iso2 : "AS" , Iso3 : "ASM", Name : "American Samoa" ),
            new Country( Iso2 : "AD" , Iso3 : "AND", Name : "Andorra" ),
            new Country( Iso2 : "AO" , Iso3 : "AGO", Name : "Angola" ),
            new Country( Iso2 : "AI" , Iso3 : "AIA", Name : "Anguilla" ),
            new Country( Iso2 : "AQ" , Iso3 : "ATA", Name : "Antarctica" ),
            new Country( Iso2 : "AG" , Iso3 : "ATG", Name : "Antigua and Barbuda" ),
            new Country( Iso2 : "AR" , Iso3 : "ARG", Name : "Argentina" ),
            new Country( Iso2 : "AM" , Iso3 : "ARM", Name : "Armenia" ),
            new Country( Iso2 : "AW" , Iso3 : "ABW", Name : "Aruba" ),
            new Country( Iso2 : "AU" , Iso3 : "AUS", Name : "Australia" ),
            new Country( Iso2 : "AT" , Iso3 : "AUT", Name : "Austria" ),
            new Country( Iso2 : "AZ" , Iso3 : "AZE", Name : "Azerbaijan" ),
            new Country( Iso2 : "BS" , Iso3 : "BHS", Name : "Bahamas" ),
            new Country( Iso2 : "BH" , Iso3 : "BHR", Name : "Bahrain" ),
            new Country( Iso2 : "BD" , Iso3 : "BGD", Name : "Bangladesh" ),
            new Country( Iso2 : "BB" , Iso3 : "BRB", Name : "Barbados" ),
            new Country( Iso2 : "BY" , Iso3 : "BLR", Name : "Belarus" ),
            new Country( Iso2 : "BE" , Iso3 : "BEL", Name : "Belgium" ),
            new Country( Iso2 : "BZ" , Iso3 : "BLZ", Name : "Belize" ),
            new Country( Iso2 : "BJ" , Iso3 : "BEN", Name : "Benin" ),
            new Country( Iso2 : "BM" , Iso3 : "BMU", Name : "Bermuda" ),
            new Country( Iso2 : "BT" , Iso3 : "BTN", Name : "Bhutan" ),
            new Country( Iso2 : "BO" , Iso3 : "BOL", Name : "Bolivia (Plurinational State of)" ),
            new Country( Iso2 : "BQ" , Iso3 : "BES", Name : "Bonaire, Sint Eustatius and Saba" ),
            new Country( Iso2 : "BA" , Iso3 : "BIH", Name : "Bosnia and Herzegovina" ),
            new Country( Iso2 : "BW" , Iso3 : "BWA", Name : "Botswana" ),
            new Country( Iso2 : "BV" , Iso3 : "BVT", Name : "Bouvet Island" ),
            new Country( Iso2 : "BR" , Iso3 : "BRA", Name : "Brazil" ),
            new Country( Iso2 : "IO" , Iso3 : "IOT", Name : "British Indian Ocean Territory" ),
            new Country( Iso2 : "BN" , Iso3 : "BRN", Name : "Brunei Darussalam" ),
            new Country( Iso2 : "BG" , Iso3 : "BGR", Name : "Bulgaria" ),
            new Country( Iso2 : "BF" , Iso3 : "BFA", Name : "Burkina Faso" ),
            new Country( Iso2 : "BI" , Iso3 : "BDI", Name : "Burundi" ),
            new Country( Iso2 : "CV" , Iso3 : "CPV", Name : "Cabo Verde" ),
            new Country( Iso2 : "KH" , Iso3 : "KHM", Name : "Cambodia" ),
            new Country( Iso2 : "CM" , Iso3 : "CMR", Name : "Cameroon" ),
            new Country( Iso2 : "CA" , Iso3 : "CAN", Name : "Canada" ),
            new Country( Iso2 : "KY" , Iso3 : "CYM", Name : "Cayman Islands" ),
            new Country( Iso2 : "CF" , Iso3 : "CAF", Name : "Central African Republic" ),
            new Country( Iso2 : "TD" , Iso3 : "TCD", Name : "Chad" ),
            new Country( Iso2 : "CL" , Iso3 : "CHL", Name : "Chile" ),
            new Country( Iso2 : "CN" , Iso3 : "CHN", Name : "China" ),
            new Country( Iso2 : "CX" , Iso3 : "CXR", Name : "Christmas Island" ),
            new Country( Iso2 : "CC" , Iso3 : "CCK", Name : "Cocos (Keeling) Islands" ),
            new Country( Iso2 : "CO" , Iso3 : "COL", Name : "Colombia" ),
            new Country( Iso2 : "KM" , Iso3 : "COM", Name : "Comoros" ),
            new Country( Iso2 : "CG" , Iso3 : "COG", Name : "Congo" ),
            new Country( Iso2 : "CD" , Iso3 : "COD", Name : "Congo, Democratic Republic of the" ),
            new Country( Iso2 : "CK" , Iso3 : "COK", Name : "Cook Islands" ),
            new Country( Iso2 : "CR" , Iso3 : "CRI", Name : "Costa Rica" ),
            new Country( Iso2 : "CI" , Iso3 : "CIV", Name : "Côte d'Ivoire" ),
            new Country( Iso2 : "HR" , Iso3 : "HRV", Name : "Croatia" ),
            new Country( Iso2 : "CU" , Iso3 : "CUB", Name : "Cuba" ),
            new Country( Iso2 : "CW" , Iso3 : "CUW", Name : "Curaçao" ),
            new Country( Iso2 : "CY" , Iso3 : "CYP", Name : "Cyprus" ),
            new Country( Iso2 : "CZ" , Iso3 : "CZE", Name : "Czechia" ),
            new Country( Iso2 : "DK" , Iso3 : "DNK", Name : "Denmark" ),
            new Country( Iso2 : "DJ" , Iso3 : "DJI", Name : "Djibouti" ),
            new Country( Iso2 : "DM" , Iso3 : "DMA", Name : "Dominica" ),
            new Country( Iso2 : "DO" , Iso3 : "DOM", Name : "Dominican Republic" ),
            new Country( Iso2 : "EC" , Iso3 : "ECU", Name : "Ecuador" ),
            new Country( Iso2 : "EG" , Iso3 : "EGY", Name : "Egypt" ),
            new Country( Iso2 : "SV" , Iso3 : "SLV", Name : "El Salvador" ),
            new Country( Iso2 : "GQ" , Iso3 : "GNQ", Name : "Equatorial Guinea" ),
            new Country( Iso2 : "ER" , Iso3 : "ERI", Name : "Eritrea" ),
            new Country( Iso2 : "EE" , Iso3 : "EST", Name : "Estonia" ),
            new Country( Iso2 : "SZ" , Iso3 : "SWZ", Name : "Eswatini" ),
            new Country( Iso2 : "ET" , Iso3 : "ETH", Name : "Ethiopia" ),
            new Country( Iso2 : "FK" , Iso3 : "FLK", Name : "Falkland Islands (Malvinas)" ),
            new Country( Iso2 : "FO" , Iso3 : "FRO", Name : "Faroe Islands" ),
            new Country( Iso2 : "FJ" , Iso3 : "FJI", Name : "Fiji" ),
            new Country( Iso2 : "FI" , Iso3 : "FIN", Name : "Finland" ),
            new Country( Iso2 : "FR" , Iso3 : "FRA", Name : "France" ),
            new Country( Iso2 : "GF" , Iso3 : "GUF", Name : "French Guiana" ),
            new Country( Iso2 : "PF" , Iso3 : "PYF", Name : "French Polynesia" ),
            new Country( Iso2 : "TF" , Iso3 : "ATF", Name : "French Southern Territories" ),
            new Country( Iso2 : "GA" , Iso3 : "GAB", Name : "Gabon" ),
            new Country( Iso2 : "GM" , Iso3 : "GMB", Name : "Gambia" ),
            new Country( Iso2 : "GE" , Iso3 : "GEO", Name : "Georgia" ),
            new Country( Iso2 : "DE" , Iso3 : "DEU", Name : "Germany" ),
            new Country( Iso2 : "GH" , Iso3 : "GHA", Name : "Ghana" ),
            new Country( Iso2 : "GI" , Iso3 : "GIB", Name : "Gibraltar" ),
            new Country( Iso2 : "GR" , Iso3 : "GRC", Name : "Greece" ),
            new Country( Iso2 : "GL" , Iso3 : "GRL", Name : "Greenland" ),
            new Country( Iso2 : "GD" , Iso3 : "GRD", Name : "Grenada" ),
            new Country( Iso2 : "GP" , Iso3 : "GLP", Name : "Guadeloupe" ),
            new Country( Iso2 : "GU" , Iso3 : "GUM", Name : "Guam" ),
            new Country( Iso2 : "GT" , Iso3 : "GTM", Name : "Guatemala" ),
            new Country( Iso2 : "GG" , Iso3 : "GGY", Name : "Guernsey" ),
            new Country( Iso2 : "GN" , Iso3 : "GIN", Name : "Guinea" ),
            new Country( Iso2 : "GW" , Iso3 : "GNB", Name : "Guinea-Bissau" ),
            new Country( Iso2 : "GY" , Iso3 : "GUY", Name : "Guyana" ),
            new Country( Iso2 : "HT" , Iso3 : "HTI", Name : "Haiti" ),
            new Country( Iso2 : "HM" , Iso3 : "HMD", Name : "Heard Island and McDonald Islands" ),
            new Country( Iso2 : "VA" , Iso3 : "VAT", Name : "Holy See" ),
            new Country( Iso2 : "HN" , Iso3 : "HND", Name : "Honduras" ),
            new Country( Iso2 : "HK" , Iso3 : "HKG", Name : "Hong Kong SAR" ),
            new Country( Iso2 : "HU" , Iso3 : "HUN", Name : "Hungary" ),
            new Country( Iso2 : "IS" , Iso3 : "ISL", Name : "Iceland" ),
            new Country( Iso2 : "IN" , Iso3 : "IND", Name : "India" ),
            new Country( Iso2 : "ID" , Iso3 : "IDN", Name : "Indonesia" ),
            new Country( Iso2 : "IR" , Iso3 : "IRN", Name : "Iran (Islamic Republic of)" ),
            new Country( Iso2 : "IQ" , Iso3 : "IRQ", Name : "Iraq" ),
            new Country( Iso2 : "IE" , Iso3 : "IRL", Name : "Ireland" ),
            new Country( Iso2 : "IM" , Iso3 : "IMN", Name : "Isle of Man" ),
            new Country( Iso2 : "IL" , Iso3 : "ISR", Name : "Israel" ),
            new Country( Iso2 : "IT" , Iso3 : "ITA", Name : "Italy" ),
            new Country( Iso2 : "JM" , Iso3 : "JAM", Name : "Jamaica" ),
            new Country( Iso2 : "JP" , Iso3 : "JPN", Name : "Japan" ),
            new Country( Iso2 : "JE" , Iso3 : "JEY", Name : "Jersey" ),
            new Country( Iso2 : "JO" , Iso3 : "JOR", Name : "Jordan" ),
            new Country( Iso2 : "KZ" , Iso3 : "KAZ", Name : "Kazakhstan" ),
            new Country( Iso2 : "KE" , Iso3 : "KEN", Name : "Kenya" ),
            new Country( Iso2 : "KI" , Iso3 : "KIR", Name : "Kiribati" ),
            new Country( Iso2 : "KP" , Iso3 : "PRK", Name : "Korea (Democratic People's Republic of)" ),
            new Country( Iso2 : "KR" , Iso3 : "KOR", Name : "Korea, Republic of" ),
            new Country( Iso2 : "KW" , Iso3 : "KWT", Name : "Kuwait" ),
            new Country( Iso2 : "KG" , Iso3 : "KGZ", Name : "Kyrgyzstan" ),
            new Country( Iso2 : "LA" , Iso3 : "LAO", Name : "Lao People's Democratic Republic" ),
            new Country( Iso2 : "LV" , Iso3 : "LVA", Name : "Latvia" ),
            new Country( Iso2 : "LB" , Iso3 : "LBN", Name : "Lebanon" ),
            new Country( Iso2 : "LS" , Iso3 : "LSO", Name : "Lesotho" ),
            new Country( Iso2 : "LR" , Iso3 : "LBR", Name : "Liberia" ),
            new Country( Iso2 : "LY" , Iso3 : "LBY", Name : "Libya" ),
            new Country( Iso2 : "LI" , Iso3 : "LIE", Name : "Liechtenstein" ),
            new Country( Iso2 : "LT" , Iso3 : "LTU", Name : "Lithuania" ),
            new Country( Iso2 : "LU" , Iso3 : "LUX", Name : "Luxembourg" ),
            new Country( Iso2 : "MO" , Iso3 : "MAC", Name : "Macao" ),
            new Country( Iso2 : "MG" , Iso3 : "MDG", Name : "Madagascar" ),
            new Country( Iso2 : "MW" , Iso3 : "MWI", Name : "Malawi" ),
            new Country( Iso2 : "MY" , Iso3 : "MYS", Name : "Malaysia" ),
            new Country( Iso2 : "MV" , Iso3 : "MDV", Name : "Maldives" ),
            new Country( Iso2 : "ML" , Iso3 : "MLI", Name : "Mali" ),
            new Country( Iso2 : "MT" , Iso3 : "MLT", Name : "Malta" ),
            new Country( Iso2 : "MH" , Iso3 : "MHL", Name : "Marshall Islands" ),
            new Country( Iso2 : "MQ" , Iso3 : "MTQ", Name : "Martinique" ),
            new Country( Iso2 : "MR" , Iso3 : "MRT", Name : "Mauritania" ),
            new Country( Iso2 : "MU" , Iso3 : "MUS", Name : "Mauritius" ),
            new Country( Iso2 : "YT" , Iso3 : "MYT", Name : "Mayotte" ),
            new Country( Iso2 : "MX" , Iso3 : "MEX", Name : "Mexico" ),
            new Country( Iso2 : "FM" , Iso3 : "FSM", Name : "Micronesia (Federated States of)" ),
            new Country( Iso2 : "MD" , Iso3 : "MDA", Name : "Moldova, Republic of" ),
            new Country( Iso2 : "MC" , Iso3 : "MCO", Name : "Monaco" ),
            new Country( Iso2 : "MN" , Iso3 : "MNG", Name : "Mongolia" ),
            new Country( Iso2 : "ME" , Iso3 : "MNE", Name : "Montenegro" ),
            new Country( Iso2 : "MS" , Iso3 : "MSR", Name : "Montserrat" ),
            new Country( Iso2 : "MA" , Iso3 : "MAR", Name : "Morocco" ),
            new Country( Iso2 : "MZ" , Iso3 : "MOZ", Name : "Mozambique" ),
            new Country( Iso2 : "MM" , Iso3 : "MMR", Name : "Myanmar" ),
            new Country( Iso2 : "NA" , Iso3 : "NAM", Name : "Namibia" ),
            new Country( Iso2 : "NR" , Iso3 : "NRU", Name : "Nauru" ),
            new Country( Iso2 : "NP" , Iso3 : "NPL", Name : "Nepal" ),
            new Country( Iso2 : "NL" , Iso3 : "NLD", Name : "Netherlands" ),
            new Country( Iso2 : "NC" , Iso3 : "NCL", Name : "New Caledonia" ),
            new Country( Iso2 : "NZ" , Iso3 : "NZL", Name : "New Zealand" ),
            new Country( Iso2 : "NI" , Iso3 : "NIC", Name : "Nicaragua" ),
            new Country( Iso2 : "NE" , Iso3 : "NER", Name : "Niger" ),
            new Country( Iso2 : "NG" , Iso3 : "NGA", Name : "Nigeria" ),
            new Country( Iso2 : "NU" , Iso3 : "NIU", Name : "Niue" ),
            new Country( Iso2 : "NF" , Iso3 : "NFK", Name : "Norfolk Island" ),
            new Country( Iso2 : "MK" , Iso3 : "MKD", Name : "North Macedonia" ),
            new Country( Iso2 : "MP" , Iso3 : "MNP", Name : "Northern Mariana Islands" ),
            new Country( Iso2 : "NO" , Iso3 : "NOR", Name : "Norway" ),
            new Country( Iso2 : "OM" , Iso3 : "OMN", Name : "Oman" ),
            new Country( Iso2 : "PK" , Iso3 : "PAK", Name : "Pakistan" ),
            new Country( Iso2 : "PW" , Iso3 : "PLW", Name : "Palau" ),
            new Country( Iso2 : "PS" , Iso3 : "PSE", Name : "Palestine, State of" ),
            new Country( Iso2 : "PA" , Iso3 : "PAN", Name : "Panama" ),
            new Country( Iso2 : "PG" , Iso3 : "PNG", Name : "Papua New Guinea" ),
            new Country( Iso2 : "PY" , Iso3 : "PRY", Name : "Paraguay" ),
            new Country( Iso2 : "PE" , Iso3 : "PER", Name : "Peru" ),
            new Country( Iso2 : "PH" , Iso3 : "PHL", Name : "Philippines" ),
            new Country( Iso2 : "PN" , Iso3 : "PCN", Name : "Pitcairn" ),
            new Country( Iso2 : "PL" , Iso3 : "POL", Name : "Poland" ),
            new Country( Iso2 : "PT" , Iso3 : "PRT", Name : "Portugal" ),
            new Country( Iso2 : "PR" , Iso3 : "PRI", Name : "Puerto Rico" ),
            new Country( Iso2 : "QA" , Iso3 : "QAT", Name : "Qatar" ),
            new Country( Iso2 : "RE" , Iso3 : "REU", Name : "Réunion" ),
            new Country( Iso2 : "RO" , Iso3 : "ROU", Name : "Romania" ),
            new Country( Iso2 : "RU" , Iso3 : "RUS", Name : "Russian Federation" ),
            new Country( Iso2 : "RW" , Iso3 : "RWA", Name : "Rwanda" ),
            new Country( Iso2 : "BL" , Iso3 : "BLM", Name : "Saint Barthélemy" ),
            new Country( Iso2 : "SH" , Iso3 : "SHN", Name : "Saint Helena, Ascension and Tristan da Cunha" ),
            new Country( Iso2 : "KN" , Iso3 : "KNA", Name : "Saint Kitts and Nevis" ),
            new Country( Iso2 : "LC" , Iso3 : "LCA", Name : "Saint Lucia" ),
            new Country( Iso2 : "MF" , Iso3 : "MAF", Name : "Saint Martin (French part)" ),
            new Country( Iso2 : "PM" , Iso3 : "SPM", Name : "Saint Pierre and Miquelon" ),
            new Country( Iso2 : "VC" , Iso3 : "VCT", Name : "Saint Vincent and the Grenadines" ),
            new Country( Iso2 : "WS" , Iso3 : "WSM", Name : "Samoa" ),
            new Country( Iso2 : "SM" , Iso3 : "SMR", Name : "San Marino" ),
            new Country( Iso2 : "ST" , Iso3 : "STP", Name : "Sao Tome and Principe" ),
            new Country( Iso2 : "SA" , Iso3 : "SAU", Name : "Saudi Arabia" ),
            new Country( Iso2 : "SN" , Iso3 : "SEN", Name : "Senegal" ),
            new Country( Iso2 : "RS" , Iso3 : "SRB", Name : "Serbia" ),
            new Country( Iso2 : "SC" , Iso3 : "SYC", Name : "Seychelles" ),
            new Country( Iso2 : "SL" , Iso3 : "SLE", Name : "Sierra Leone" ),
            new Country( Iso2 : "SG" , Iso3 : "SGP", Name : "Singapore" ),
            new Country( Iso2 : "SX" , Iso3 : "SXM", Name : "Sint Maarten (Dutch part)" ),
            new Country( Iso2 : "SK" , Iso3 : "SVK", Name : "Slovakia" ),
            new Country( Iso2 : "SI" , Iso3 : "SVN", Name : "Slovenia" ),
            new Country( Iso2 : "SB" , Iso3 : "SLB", Name : "Solomon Islands" ),
            new Country( Iso2 : "SO" , Iso3 : "SOM", Name : "Somalia" ),
            new Country( Iso2 : "ZA" , Iso3 : "ZAF", Name : "South Africa" ),
            new Country( Iso2 : "GS" , Iso3 : "SGS", Name : "South Georgia and the South Sandwich Islands" ),
            new Country( Iso2 : "SS" , Iso3 : "SSD", Name : "South Sudan" ),
            new Country( Iso2 : "ES" , Iso3 : "ESP", Name : "Spain" ),
            new Country( Iso2 : "LK" , Iso3 : "LKA", Name : "Sri Lanka" ),
            new Country( Iso2 : "SD" , Iso3 : "SDN", Name : "Sudan" ),
            new Country( Iso2 : "SR" , Iso3 : "SUR", Name : "Suriname" ),
            new Country( Iso2 : "SJ" , Iso3 : "SJM", Name : "Svalbard and Jan Mayen" ),
            new Country( Iso2 : "SE" , Iso3 : "SWE", Name : "Sweden" ),
            new Country( Iso2 : "CH" , Iso3 : "CHE", Name : "Switzerland" ),
            new Country( Iso2 : "SY" , Iso3 : "SYR", Name : "Syrian Arab Republic" ),
            new Country( Iso2 : "TW" , Iso3 : "TWN", Name : "Taiwan, Province of China" ),
            new Country( Iso2 : "TJ" , Iso3 : "TJK", Name : "Tajikistan" ),
            new Country( Iso2 : "TZ" , Iso3 : "TZA", Name : "Tanzania, United Republic of" ),
            new Country( Iso2 : "TH" , Iso3 : "THA", Name : "Thailand" ),
            new Country( Iso2 : "TL" , Iso3 : "TLS", Name : "Timor-Leste" ),
            new Country( Iso2 : "TG" , Iso3 : "TGO", Name : "Togo" ),
            new Country( Iso2 : "TK" , Iso3 : "TKL", Name : "Tokelau" ),
            new Country( Iso2 : "TO" , Iso3 : "TON", Name : "Tonga" ),
            new Country( Iso2 : "TT" , Iso3 : "TTO", Name : "Trinidad and Tobago" ),
            new Country( Iso2 : "TN" , Iso3 : "TUN", Name : "Tunisia" ),
            new Country( Iso2 : "TR" , Iso3 : "TUR", Name : "Turkey" ),
            new Country( Iso2 : "TM" , Iso3 : "TKM", Name : "Turkmenistan" ),
            new Country( Iso2 : "TC" , Iso3 : "TCA", Name : "Turks and Caicos Islands" ),
            new Country( Iso2 : "TV" , Iso3 : "TUV", Name : "Tuvalu" ),
            new Country( Iso2 : "UG" , Iso3 : "UGA", Name : "Uganda" ),
            new Country( Iso2 : "UA" , Iso3 : "UKR", Name : "Ukraine" ),
            new Country( Iso2 : "AE" , Iso3 : "ARE", Name : "United Arab Emirates" ),
            new Country( Iso2 : "GB" , Iso3 : "GBR", Name : "United Kingdom of Great Britain and Northern Ireland" ),
            new Country( Iso2 : "US" , Iso3 : "USA", Name : "United States of America" ),
            new Country( Iso2 : "UM" , Iso3 : "UMI", Name : "United States Minor Outlying Islands" ),
            new Country( Iso2 : "UY" , Iso3 : "URY", Name : "Uruguay" ),
            new Country( Iso2 : "UZ" , Iso3 : "UZB", Name : "Uzbekistan" ),
            new Country( Iso2 : "VU" , Iso3 : "VUT", Name : "Vanuatu" ),
            new Country( Iso2 : "VE" , Iso3 : "VEN", Name : "Venezuela (Bolivarian Republic of)" ),
            new Country( Iso2 : "VN" , Iso3 : "VNM", Name : "Viet Nam" ),
            new Country( Iso2 : "VG" , Iso3 : "VGB", Name : "Virgin Islands (British)" ),
            new Country( Iso2 : "VI" , Iso3 : "VIR", Name : "Virgin Islands (U.S.)" ),
            new Country( Iso2 : "WF" , Iso3 : "WLF", Name : "Wallis and Futuna" ),
            new Country( Iso2 : "EH" , Iso3 : "ESH", Name : "Western Sahara" ),
            new Country( Iso2 : "YE" , Iso3 : "YEM", Name : "Yemen" ),
            new Country( Iso2 : "ZM" , Iso3 : "ZMB", Name : "Zambia" ),
            new Country( Iso2 : "ZW" , Iso3 : "ZWE", Name : "Zimbabwe" ),
    };
}
